### ISSUE TITLE
Frontend side of this doesn't work

### ISSUE THREAD

**Issue by TomBebb** [Fire-The-Fox/Own-Nuxt-Like-Framework#1]
Environment: Ubuntu 22.04 under WSL

```
tom@Tom-D-PC:~/Own-Nuxt-Like-Framework$ bun run index.ts 
][ INFO ]: Loading config
[ INFO ]: Configuring build system
[ DONE ]: Build system configured
[ INFO ]: Loading plugins
[ DONE ]: Plugin "vue" was loaded!
[ DONE ]: Plugin "css" was loaded!
[ DONE ]: Plugins loaded
[ INFO ]: Starting up the build system
[ INFO ]: Transpiling
[ DONE ]: Finished transpilation
[ INFO ]: Generating pages
[ DONE ]: Pages generated
[ INFO ]: Bundling pages
[ DONE ]: Pages bundled
```
tom@Tom-D-PC:~/Own-Nuxt-Like-Framework$ curl http://localhost:3000/api/test/wildcard/hi
http://localhost:3000/api/test/wildcard/hi

Instead of showing the index page, I am shown this:
NOT_FOUND

**Comment by LowByteFox** [comment]
Interesting, let me take a look

Have you applied the patch?

**Comment by LowByteFox** [comment]
The patch is `sed -i "s/this.builder.prepare();/this.builder.prepare(this.config?.dirs ?? ['public']);/" node_modules/buchta/src/buchta.ts`

**Comment by LowByteFox** [comment]
Everything will work fine, either use the patch or update buchta to 0.5.100
